/* To change this license header, choose License Headers in Project Properties. To change this template file, choose Tools | Templates and open the template in
 * the editor. */
package chatClient;

import java.awt.Color;
import java.awt.GraphicsConfiguration;
import java.util.Vector;

import javax.swing.JTextPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultStyledDocument;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;

import common.StyledDoc;

/**
 *
 * @author Administrator
 */
public class ClientGui extends javax.swing.JFrame {

	Client		client	= null;
	//	StyleContext				sc;
	//	final DefaultStyledDocument	doc;
	StyledDoc	sd;

	DefaultTableModel	chatList	= new DefaultTableModel() {
		@Override
		public boolean isCellEditable(int row, int column) {			//수정불가 처리
			if (column >= 0) {
				return false;
			} else {
				return true;
			}
		}
	};
	DefaultTableModel	userList	= new DefaultTableModel() {
		@Override
		public boolean isCellEditable(int row, int column) {			//수정불가 처리
			if (column >= 0) {
				return false;
			} else {
				return true;
			}
		}
	};

	/**
	 * Creates new form ClientGui
	 */
	public ClientGui(Client client) {
		this.client = client;
		//		sc = new StyleContext();
		//		doc = new DefaultStyledDocument(sc);
		initComponents();
		sd = new StyledDoc(jTextPane1);
		//		jTextPane1 = new JTextPane(doc);
		//		jTextPane1.setBackground(Color.black);

	}

	public void logAdd(String log, String style) {
		sd.addADocEnd(log + "\n", style);
		jScrollPane1.getVerticalScrollBar().setValue(jScrollPane1.getVerticalScrollBar().getMaximum());
	}

	public void logAdd(String log) {
		sd.addADocEnd(log + "\n", sd.white);
		jScrollPane1.getVerticalScrollBar().setValue(jScrollPane1.getVerticalScrollBar().getMaximum());
		//		final Style heading2Style = sc.addStyle("Heading2", null);
		//		heading2Style.addAttribute(StyleConstants.Foreground, Color.red);
		//		heading2Style.addAttribute(StyleConstants.FontSize, new Integer(16));
		//		heading2Style.addAttribute(StyleConstants.FontFamily, "serif");
		//		heading2Style.addAttribute(StyleConstants.Bold, new Boolean(true));
		//		setEndline();
		//		//		jTextPane1.replaceSelection(log + "\n");
		//		//		jTextPane1.replaceSelection(content);
		//		//		jTextPane1.insert
		//		try {
		//			//			System.out.println(log);
		//			doc.insertString(doc.getLength(), log + "\n", heading2Style);
		//		} catch (BadLocationException e) {
		//			// TODO Auto-generated catch block
		//			e.printStackTrace();
		//		}
	}

	//	private void setEndline() {//그냥 억지로 함수 하나 만들었어요.
	//		// TODO Auto-generated method stub
	//		jTextPane1.selectAll();
	//		//문장의 끝에 무조건 커서 이동하게 설정
	//		jTextPane1.setSelectionStart(jTextPane1.getSelectionEnd());
	//	}

	public void chatListSet(String[][] list) {
		// TODO Auto-generated method stub
		String[] columnNames = new String[3];

		columnNames[0] = "no";
		columnNames[1] = "name";
		columnNames[2] = "boss";

		chatList.setDataVector(list, columnNames);
	}

	public void userListSet(String[][] list) {
		// TODO Auto-generated method stub
		String[] columnNames = new String[2];

		columnNames[0] = "id";
		columnNames[1] = "nick";

		userList.setDataVector(list, columnNames);
	}

	public String getRoomName(String key) {
		// TODO Auto-generated method stub
		//		chatList.
		//		roomTable.
		for (int i = 0; i < chatList.getRowCount(); i++) {
			String tt = (String) chatList.getValueAt(i, 0);
			if (key.equals(tt)) {
				return (String) chatList.getValueAt(i, 1);
			}
		}
		return null;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        roomTable = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        roomJoinBt = new javax.swing.JButton();
        roomCreateBt = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        nickbt = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        userCreate = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client");
        setPreferredSize(new java.awt.Dimension(600, 400));
        setSize(new java.awt.Dimension(300, 400));

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane1.setResizeWeight(0.5);

        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(100, 23));

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTextPane1);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jPanel4.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        roomTable.setModel(chatList);
        roomTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        roomTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(roomTable);

        jPanel4.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel6.setLayout(new java.awt.GridLayout(0, 1));

        roomJoinBt.setText("방 들어가기");
        roomJoinBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomJoinBtActionPerformed(evt);
            }
        });
        jPanel6.add(roomJoinBt);

        roomCreateBt.setText("방만들기");
        roomCreateBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomCreateBtActionPerformed(evt);
            }
        });
        jPanel6.add(roomCreateBt);

        jPanel4.add(jPanel6, java.awt.BorderLayout.SOUTH);

        jPanel3.add(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        userTable.setModel(userList);
        jScrollPane3.setViewportView(userTable);

        jPanel5.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        nickbt.setText("닉네임 변경");
        nickbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nickbtActionPerformed(evt);
            }
        });
        jPanel5.add(nickbt, java.awt.BorderLayout.SOUTH);

        jPanel3.add(jPanel5);

        jSplitPane1.setRightComponent(jPanel3);

        jPanel1.add(jSplitPane1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        userCreate.setLabel("회원가입");
        userCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userCreateActionPerformed(evt);
            }
        });
        jPanel2.add(userCreate);

        jButton1.setText("로그인");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jLabel1.setText("미구현");
        jPanel2.add(jLabel1);

        jTextField1.setPreferredSize(new java.awt.Dimension(50, 21));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		client.login();
	}//GEN-LAST:event_jButton1ActionPerformed

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
		// TODO add your handling code here:
		System.out.println("jTextField1ActionPerformed");
	}//GEN-LAST:event_jTextField1ActionPerformed

	private void roomTableMouseClicked(java.awt.event.MouseEvent e) {//GEN-FIRST:event_roomTableMouseClicked
		// TODO add your handling code here:
		//		System.out.println("getClickCount"+e.getClickCount());
		if (e.getClickCount() >= 2) {// 더블클릭
			//			System.out.println("roomTableMouseClicked");
			String t = (String) roomTable.getValueAt(roomTable.getSelectedRow(), 0);
			//			System.out.println("f:"+t);
			client.roomJoin(t);
		}
	}//GEN-LAST:event_roomTableMouseClicked

	private void roomJoinBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomJoinBtActionPerformed
		// TODO add your handling code here:
		String t = (String) roomTable.getValueAt(roomTable.getSelectedRow(), 0);
		//			System.out.println("f:"+t);
		client.roomJoin(t);
	}//GEN-LAST:event_roomJoinBtActionPerformed

	private void roomCreateBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomCreateBtActionPerformed
		// TODO add your handling code here:

		client.roomCreate();
	}//GEN-LAST:event_roomCreateBtActionPerformed

	private void userCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userCreateActionPerformed
		// TODO add your handling code here:
		client.userCreate();
	}//GEN-LAST:event_userCreateActionPerformed

	private void nickbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nickbtActionPerformed
		// TODO add your handling code here:
		client.userNickChange();
	}//GEN-LAST:event_nickbtActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ClientGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ClientGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ClientGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ClientGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				//new ClientGui().setVisible(true);
			}
		});
		new Client();
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton nickbt;
    private javax.swing.JButton roomCreateBt;
    private javax.swing.JButton roomJoinBt;
    private javax.swing.JTable roomTable;
    private javax.swing.JButton userCreate;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables

}
