/* To change this license header, choose License Headers in Project Properties. To change this template file, choose Tools | Templates and open the template in
 * the editor. */
package chatSever;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Vector;

import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

import common.StyledDoc;
import javax.swing.ScrollPaneConstants;

/**
 *
 * @author Administrator
 */
public class ServerGui extends javax.swing.JFrame {

	DefaultTableModel	clientsList	= new DefaultTableModel();
	DefaultTableModel	chatList	= new DefaultTableModel();
	Server				server;
	StyledDoc			sd;

	/**
	 * Creates new form ServerGui
	 */
	public ServerGui() {

		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
		} catch (InstantiationException ex) {
		} catch (IllegalAccessException ex) {
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
		}
		initComponents();
		sd = new StyledDoc(jTextPane1);
	}

	public ServerGui(Server server) {
		this.server = server;

		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
		} catch (InstantiationException ex) {
		} catch (IllegalAccessException ex) {
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
		}
		initComponents();
		sd = new StyledDoc(jTextPane1);
	}

	public void logAdd(String log) {
		//		setEndline();
		//		jTextPane1.replaceSelection(log + "\n");
		sd.addADocEnd(log + "\n");
		jScrollPane1.getVerticalScrollBar().setValue(jScrollPane1.getVerticalScrollBar().getMaximum());
	}

	public void logAdd(String log, String style) {
		//		setEndline();
		//		jTextPane1.replaceSelection(log + "\n");
		sd.addADocEnd(log + "\n", style);
		jScrollPane1.getVerticalScrollBar().setValue(jScrollPane1.getVerticalScrollBar().getMaximum());
	}

	public void clientListSet(List<ServerClient> List) {
		//		System.out.println("clientListSet1");
		Vector<String> columnNames = new Vector<String>();

		columnNames.add("id");
		columnNames.add("nick");

		// data of the table
		Vector<Vector<String>> data = new Vector<Vector<String>>();

		for (ServerClient client : List) {
			System.out.println(client);

			Vector<String> vector = new Vector<String>();

			vector.add(client.GetId());
			vector.add(client.GetNick());

			data.add(vector);
		}
		clientsList.setDataVector(data, columnNames);

	}

	public void chatListSet(Map<String, ServerChat> List) {
		//		System.out.println("chatListSet1");

		Vector<String> columnNames = new Vector<String>();

		columnNames.add("boss");
		columnNames.add("name");

		// data of the table
		Vector<Vector<String>> data = new Vector<Vector<String>>();

		for (String key : List.keySet()) {
			//            System.out.println( String.format("키 : %s, 값 : %s", key, map.get(key)) );
			//        }
			//		for (ServerChat chat : List) {
			//			System.out.println(chat);

			Vector<String> vector = new Vector<String>();

			//			vector.add(chat.GetId());
			vector.add(List.get(key).GetBossName());
			vector.add(List.get(key).GetRoomName());

			data.add(vector);
		}
		chatList.setDataVector(data, columnNames);

	}

	private void setEndline() {//그냥 억지로 함수 하나 만들었어요.
		// TODO Auto-generated method stub
		jTextPane1.selectAll();
		//문장의 끝에 무조건 커서 이동하게 설정
		jTextPane1.setSelectionStart(jTextPane1.getSelectionEnd());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        jScrollPane1 = new JScrollPane();
        jTextPane1 = new JTextPane();
        jScrollPane2 = new JScrollPane();
        jTable1 = new JTable();
        jScrollPane3 = new JScrollPane();
        jTable2 = new JTable();
        jPanel2 = new JPanel();
        jLabel1 = new JLabel();
        jTextField1 = new JTextField();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new Dimension(600, 400));
        setSize(new Dimension(300, 600));
        addWindowListener(new WindowAdapter() {
            public void windowClosed(WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new GridLayout(1, 0));

        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setViewportView(jTextPane1);

        jPanel1.add(jScrollPane1);

        jTable1.setModel(clientsList);
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2);

        jTable2.setModel(chatList);
        jScrollPane3.setViewportView(jTable2);

        jPanel1.add(jScrollPane3);

        getContentPane().add(jPanel1, BorderLayout.CENTER);

        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1);

        jTextField1.setText("jTextField1");
        jTextField1.setPreferredSize(new Dimension(100, 30));
        jTextField1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1);

        getContentPane().add(jPanel2, BorderLayout.SOUTH);
        jPanel2.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void formWindowClosing(WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
		// TODO add your handling code here:
		//		server.close();
		System.out.println("tsatd123");
	}//GEN-LAST:event_formWindowClosing

	private void formWindowClosed(WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
		// TODO add your handling code here:
		System.out.println("tsatd");
	}//GEN-LAST:event_formWindowClosed

	private void jTextField1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
		// TODO add your handling code here:
		System.out.println("jTextField1ActionPerformed");
	}//GEN-LAST:event_jTextField1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ServerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ServerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ServerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ServerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				//				new ServerGui(null).setVisible(true);
				new Server();
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    JLabel jLabel1;
    JPanel jPanel1;
    JPanel jPanel2;
    JScrollPane jScrollPane1;
    JScrollPane jScrollPane2;
    JScrollPane jScrollPane3;
    JTable jTable1;
    JTable jTable2;
    JTextField jTextField1;
    JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
